[book]
authors = ["Igor Anpilogov"]
language = "en"
multilingual = false
src = "src"
title = "Anomaly Modding Book"

[output.html]
git-repository-url = "https://github.com/Igigog/anomaly-modding-book"
site-url = "/anomaly-modding-book/"
